language: bash
dist: trusty
addons:
  apt:
    packages:
    - whois
    - gawk
    - mawk
    - original-awk
    - mksh
    - posh
    - dash
    - bash

matrix:
  fast_finish: true

env:
  - AWK=awk
  - AWK=mawk
  - AWK=gawk
  - AWK=original-awk
  - SH=sh
  - SH=mksh
  - SH=posh
  - SH=dash
  - SH=bash

script:
  - shellcheck check_domain.sh
  # shell check knows only certain syntaxes
  - 'case "$SH" in sh|bash|dash|ksh) shellcheck -s $SH check_domain.sh;; esac'
  - ./test.sh

# vim:ts=2:sw=2:et
